import {
  ComponentFixture,
  fakeAsync,
  TestBed,
  tick,
} from '@angular/core/testing';

import { VkTreeComponent } from './vk-tree.component';

import { MatDivider } from '@angular/material/divider';
import { MatFormField } from '@angular/material/form-field';
import { FormsModule } from '@angular/forms';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInput } from '@angular/material/input';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { VkSearchComponent } from '../vk-search/vk-search.component';
import { MatCheckbox, MatCheckboxModule } from '@angular/material/checkbox';
import {
  MatCard,
  MatCardSubtitle,
  MatCardHeader,
  MatCardTitle,
  MatCardActions,
  MatCardContent,
} from '@angular/material/card';
import { MatIconModule } from '@angular/material/icon';
describe('VkTreeComponent', () => {
  let component: VkTreeComponent;
  let fixture: ComponentFixture<VkTreeComponent>;

  beforeEach(async () => {
    await TestBed.configureTestingModule({
      imports: [
        MatCard,
        MatCardSubtitle,
        MatCardHeader,
        MatCardTitle,
        MatCardActions,
        MatCardContent,
        MatDivider,
        MatFormField,
        FormsModule,
        MatFormFieldModule,
        MatInput,
        MatCheckbox,
        MatCheckboxModule,
        BrowserAnimationsModule,
        MatIconModule,
      ],
      declarations: [VkTreeComponent, VkSearchComponent],
    }).compileComponents();

    fixture = TestBed.createComponent(VkTreeComponent);
    component = fixture.componentInstance;
    component.dataSource = treeDataSource;
    component.ngOnInit();
    fixture.detectChanges();
  });
  //mdc-label
  it('should create', () => {
    expect(component).toBeTruthy();
  });
  it('should verify checkbox label', fakeAsync(() => {
    expect(component.dataSource.length).toEqual(15);
    const content = fixture.nativeElement.querySelectorAll('.mdc-label');
    expect(content[0].innerHTML.trim()).toEqual('General Information');
    //expect(content).toContain('Customer Contac');
  }));
  it('verify search function', () => {
    // var searchInput = fixture.nativeElement.getElementById('mat-input-0');
    // searchInput.value = 'serial';
    fixture.detectChanges();
    const content = fixture.nativeElement.querySelectorAll('.mdc-label');
    expect(content[0].innerHTML.trim()).toEqual('General Information');
  });
});
const treeDataSource = [
  {
    displayName: 'General Information',
    name: 'General',
    expand: false,
    checked: false,
    indeterminate: false,
    display: true,
    field: '',
    children: [
      {
        display: true,
        indeterminate: false,
        expand: false,
        displayName: 'Tag Number',
        name: 'General Information',
        checked: false,
        field: 'tag_number',
        children: [],
      },
      {
        name: 'General Information',
        displayName: 'Serial Number',
        checked: false,
        display: true,
        indeterminate: false,
        expand: false,
        field: 'serial_number',
        children: [],
      },
      {
        name: 'General Information',
        displayName: 'Item Number',
        checked: false,
        display: true,
        indeterminate: false,
        expand: false,
        field: 'part_number',
        children: [],
      },
      {
        name: 'General Information',
        displayName: 'Installation Application',
        checked: false,
        display: true,
        indeterminate: false,
        expand: false,
        field: 'installation_app',
        children: [],
      },
      {
        name: 'General Information',
        displayName: 'Owner',
        checked: false,
        display: true,
        indeterminate: false,
        expand: false,
        field: 'process_fluid',
        children: [],
      },
      {
        name: 'General Information',
        displayName: 'Plant',
        checked: false,
        display: true,
        indeterminate: false,
        expand: false,
        field: 'plant',
        children: [],
      },
      {
        name: 'General Information',
        displayName: 'Unit / Vessel',
        checked: false,
        display: true,
        indeterminate: false,
        expand: false,
        field: 'unit',
        children: [],
      },
      {
        name: 'General Information',
        displayName: 'Location',
        checked: false,
        display: true,
        indeterminate: false,
        expand: false,
        field: 'location',
        children: [],
      },
      {
        name: 'General Information',
        displayName: 'Job Number',
        checked: false,
        display: true,
        indeterminate: false,
        expand: false,
        field: 'job_number',
        children: [],
      },
    ],
  },
  {
    displayName: 'Customer Contact',
    name: 'General',
    expand: false,
    checked: false,
    indeterminate: false,
    display: true,
    field: '',
    children: [
      {
        display: true,
        indeterminate: false,
        expand: false,
        displayName: 'Name',
        name: 'Customer Contact',
        checked: false,
        field: 'customer',
        children: [],
      },
      {
        name: 'Customer Contact',
        displayName: 'Phone',
        checked: false,
        display: true,
        indeterminate: false,
        expand: false,
        field: 'customer_phone',
        children: [],
      },
      {
        name: 'Customer Contact',
        displayName: 'Email',
        checked: false,
        display: true,
        indeterminate: false,
        expand: false,
        field: 'customer_email',
        children: [],
      },
    ],
  },
  {
    displayName: 'Sales Order Details',
    name: 'General',
    expand: false,
    checked: false,
    indeterminate: false,
    display: true,
    field: '',
    children: [
      {
        display: true,
        indeterminate: false,
        expand: false,
        displayName: 'Order Number',
        name: 'Sales Order Details',
        checked: false,
        field: 'sales_order_number',
        children: [],
      },
      {
        name: 'Sales Order Details',
        displayName: 'Industry',
        checked: false,
        display: true,
        indeterminate: false,
        expand: false,
        field: 'industry',
        children: [],
      },
      {
        name: 'Sales Order Details',
        displayName: 'Customer PO Number',
        checked: false,
        display: true,
        indeterminate: false,
        expand: false,
        field: 'customer_po_number',
        children: [],
      },
      {
        name: 'Sales Order Details',
        displayName: 'Source Factory',
        checked: false,
        display: true,
        indeterminate: false,
        expand: false,
        field: 'source_factory',
        children: [],
      },
      {
        name: 'Sales Order Details',
        displayName: 'Sales Rep Name',
        checked: false,
        display: true,
        indeterminate: false,
        expand: false,
        field: 'sales_rep_name',
        children: [],
      },
      {
        name: 'Sales Order Details',
        displayName: 'P&ID',
        checked: false,
        display: true,
        indeterminate: false,
        expand: false,
        field: 'p&id',
        children: [],
      },
    ],
  },
  {
    displayName: 'End User Details',
    name: 'General',
    expand: false,
    checked: false,
    indeterminate: false,
    display: true,
    field: '',
    children: [
      {
        display: true,
        indeterminate: false,
        expand: false,
        displayName: 'User Name',
        name: 'End User Details',
        checked: false,
        field: 'end_user',
        children: [],
      },
      {
        name: 'End User Details',
        displayName: 'User Address',
        checked: false,
        display: true,
        indeterminate: false,
        expand: false,
        field: 'end_user_address',
        children: [],
      },
      {
        name: 'End User Details',
        displayName: 'Country',
        checked: false,
        display: true,
        indeterminate: false,
        expand: false,
        field: 'end_user_country',
        children: [],
      },
      {
        name: 'End User Details',
        displayName: 'Region',
        checked: false,
        display: true,
        indeterminate: false,
        expand: false,
        field: 'end_user_region',
        children: [],
      },
      {
        name: 'End User Details',
        displayName: 'State/Province',
        checked: false,
        display: true,
        indeterminate: false,
        expand: false,
        field: 'end_user_state',
        children: [],
      },
      {
        name: 'End User Details',
        displayName: 'Zip Code',
        checked: false,
        display: true,
        indeterminate: false,
        expand: false,
        field: 'end_user_zip_code',
        children: [],
      },
      {
        name: 'End User Details',
        displayName: 'Project Name',
        checked: false,
        display: true,
        indeterminate: false,
        expand: false,
        field: 'project_name',
        children: [],
      },
    ],
  },
  {
    displayName: 'Shipped To',
    name: 'General',
    expand: false,
    checked: false,
    indeterminate: false,
    display: true,
    field: '',
    children: [
      {
        display: true,
        indeterminate: false,
        expand: false,
        displayName: 'User Name',
        name: 'Shipped To',
        checked: false,
        field: 'ship_to',
        children: [],
      },
      {
        name: 'Shipped To',
        displayName: 'Address',
        checked: false,
        display: true,
        indeterminate: false,
        expand: false,
        field: 'ship_to_address',
        children: [],
      },
      {
        name: 'Shipped To',
        displayName: 'Country',
        checked: false,
        display: true,
        indeterminate: false,
        expand: false,
        field: 'ship_to_country',
        children: [],
      },
      {
        name: 'Shipped To',
        displayName: 'Region',
        checked: false,
        display: true,
        indeterminate: false,
        expand: false,
        field: 'ship_to_region',
        children: [],
      },
      {
        name: 'Shipped To',
        displayName: 'State/Province',
        checked: false,
        display: true,
        indeterminate: false,
        expand: false,
        field: 'ship_to_state',
        children: [],
      },
      {
        name: 'Shipped To',
        displayName: 'Zip Code',
        checked: false,
        display: true,
        indeterminate: false,
        expand: false,
        field: 'ship_to_zip_code',
        children: [],
      },
    ],
  },
  {
    displayName: 'Sold To',
    name: 'General',
    expand: false,
    checked: false,
    indeterminate: false,
    display: true,
    field: '',
    children: [
      {
        display: true,
        indeterminate: false,
        expand: false,
        displayName: 'User Name',
        name: 'Sold To',
        checked: false,
        field: 'sold_to',
        children: [],
      },
      {
        name: 'Sold To',
        displayName: 'Address',
        checked: false,
        display: true,
        indeterminate: false,
        expand: false,
        field: 'sold_to_address',
        children: [],
      },
      {
        name: 'Sold To',
        displayName: 'Country',
        checked: false,
        display: true,
        indeterminate: false,
        expand: false,
        field: 'sold_to_country',
        children: [],
      },
      {
        name: 'Sold To',
        displayName: 'Region',
        checked: false,
        display: true,
        indeterminate: false,
        expand: false,
        field: 'sold_to_region',
        children: [],
      },
      {
        name: 'Sold To',
        displayName: 'State/Province',
        checked: false,
        display: true,
        indeterminate: false,
        expand: false,
        field: 'sold_to_state',
        children: [],
      },
      {
        name: 'Sold To',
        displayName: 'Zip Code',
        checked: false,
        display: true,
        indeterminate: false,
        expand: false,
        field: 'sold_to_zip_code',
        children: [],
      },
    ],
  },
  {
    displayName: 'Valve Configuration',
    name: 'CV',
    expand: false,
    checked: false,
    indeterminate: false,
    display: true,
    field: '',
    children: [
      {
        display: true,
        indeterminate: false,
        expand: false,
        displayName: 'Manufacturer',
        name: 'Valve Configuration',
        checked: false,
        field: 'manufacturer',
        children: [],
      },
      {
        name: 'Valve Configuration',
        displayName: 'Model Number',
        checked: false,
        display: true,
        indeterminate: false,
        expand: false,
        field: 'model_number',
        children: [],
      },
      {
        name: 'Valve Configuration',
        displayName: 'Product Family',
        checked: false,
        display: true,
        indeterminate: false,
        expand: false,
        field: 'product_family',
        children: [],
      },
      {
        name: 'Valve Configuration',
        displayName: 'Body Size',
        checked: false,
        display: true,
        indeterminate: false,
        expand: false,
        field: 'body_size',
        children: [],
      },
      {
        name: 'Valve Configuration',
        displayName: 'Inlet Size',
        checked: false,
        display: true,
        indeterminate: false,
        expand: false,
        field: 'inlet_size',
        children: [],
      },
      {
        name: 'Valve Configuration',
        displayName: 'Outlet Size',
        checked: false,
        display: true,
        indeterminate: false,
        expand: false,
        field: 'outlet_size',
        children: [],
      },
      {
        name: 'Valve Configuration',
        displayName: 'Valve Cv',
        checked: false,
        display: true,
        indeterminate: false,
        expand: false,
        field: 'cv',
        children: [],
      },
      {
        name: 'Valve Configuration',
        displayName: 'Body Material',
        checked: false,
        display: true,
        indeterminate: false,
        expand: false,
        field: 'body_material',
        children: [],
      },
      {
        name: 'Valve Configuration',
        displayName: 'Pressure Class',
        checked: false,
        display: true,
        indeterminate: false,
        expand: false,
        field: 'pressure_class',
        children: [],
      },
      {
        name: 'Valve Configuration',
        displayName: 'Model Series',
        checked: false,
        display: true,
        indeterminate: false,
        expand: false,
        field: 'model_series',
        children: [],
      },
      {
        name: 'Valve Configuration',
        displayName: 'Flange Face',
        checked: false,
        display: true,
        indeterminate: false,
        expand: false,
        field: 'flange_face',
        children: [],
      },
      {
        name: 'Valve Configuration',
        displayName: 'Flow Direction',
        checked: false,
        display: true,
        indeterminate: false,
        expand: false,
        field: 'flow_direction',
        children: [],
      },
      {
        name: 'Valve Configuration',
        displayName: 'Leakage Class',
        checked: false,
        display: true,
        indeterminate: false,
        expand: false,
        field: 'leakage_class',
        children: [],
      },
    ],
  },
  {
    displayName: 'Process',
    name: 'CV',
    expand: false,
    checked: false,
    indeterminate: false,
    display: true,
    field: '',
    children: [
      {
        display: true,
        indeterminate: false,
        expand: false,
        displayName: 'CV Service',
        name: 'Process',
        checked: false,
        field: 'service_cv',
        children: [],
      },
      {
        name: 'Process',
        displayName: 'Process Fluid',
        checked: false,
        display: true,
        indeterminate: false,
        expand: false,
        field: 'process_fluid',
        children: [],
      },
    ],
  },
  {
    displayName: 'Positioner Configuration',
    name: 'CV',
    expand: false,
    checked: false,
    indeterminate: false,
    display: true,
    field: '',
    children: [
      {
        display: true,
        indeterminate: false,
        expand: false,
        displayName: 'Serial Number',
        name: 'Positioner Configuration',
        checked: false,
        field: 'positioner_serial_number',
        children: [],
      },
      {
        name: 'Positioner Configuration',
        displayName: 'Tag',
        checked: false,
        display: true,
        indeterminate: false,
        expand: false,
        field: 'positioner_tag_number',
        children: [],
      },
      {
        name: 'Positioner Configuration',
        displayName: 'Model Number',
        checked: false,
        display: true,
        indeterminate: false,
        expand: false,
        field: 'positioner_model_number',
        children: [],
      },
      {
        name: 'Positioner Configuration',
        displayName: 'Product Family',
        checked: false,
        display: true,
        indeterminate: false,
        expand: false,
        field: 'positioner_product_family',
        children: [],
      },
      {
        name: 'Positioner Configuration',
        displayName: 'Model Series',
        checked: false,
        display: true,
        indeterminate: false,
        expand: false,
        field: 'positioner_model_series',
        children: [],
      },
      {
        name: 'Positioner Configuration',
        displayName: 'Action',
        checked: false,
        display: true,
        indeterminate: false,
        expand: false,
        field: 'positioner_single_double',
        children: [],
      },
      {
        name: 'Positioner Configuration',
        displayName: 'Firmware Version',
        checked: false,
        display: true,
        indeterminate: false,
        expand: false,
        field: 'positioner_firmware_version',
        children: [],
      },
      {
        name: 'Positioner Configuration',
        displayName: 'HART Version',
        checked: false,
        display: true,
        indeterminate: false,
        expand: false,
        field: 'positioner_hart_version',
        children: [],
      },
      {
        name: 'Positioner Configuration',
        displayName: 'Diagnostics Level',
        checked: false,
        display: true,
        indeterminate: false,
        expand: false,
        field: 'positioner_diagnostics_level',
        children: [],
      },
    ],
  },
  {
    displayName: 'Actuator Configuration',
    name: 'CV',
    expand: false,
    checked: false,
    indeterminate: false,
    display: true,
    field: '',
    children: [
      {
        display: true,
        indeterminate: false,
        expand: false,
        displayName: 'Serial Number',
        name: 'Actuator Configuration',
        checked: false,
        field: 'actuator_serial_number',
        children: [],
      },
      {
        name: 'Actuator Configuration',
        displayName: 'Tag',
        checked: false,
        display: true,
        indeterminate: false,
        expand: false,
        field: 'actuator_tag_number',
        children: [],
      },
      {
        name: 'Actuator Configuration',
        displayName: 'Manufacturer',
        checked: false,
        display: true,
        indeterminate: false,
        expand: false,
        field: 'actuator_manufacturer',
        children: [],
      },
      {
        name: 'Actuator Configuration',
        displayName: 'Model Number',
        checked: false,
        display: true,
        indeterminate: false,
        expand: false,
        field: 'actuator_model',
        children: [],
      },
      {
        name: 'Actuator Configuration',
        displayName: 'Product Family',
        checked: false,
        display: true,
        indeterminate: false,
        expand: false,
        field: 'actuator_product_family',
        children: [],
      },
      {
        name: 'Actuator Configuration',
        displayName: 'Model Series',
        checked: false,
        display: true,
        indeterminate: false,
        expand: false,
        field: 'actuator_model_series',
        children: [],
      },
      {
        name: 'Actuator Configuration',
        displayName: 'Fail Position',
        checked: false,
        display: true,
        indeterminate: false,
        expand: false,
        field: 'fail_position',
        children: [],
      },
      {
        name: 'Actuator Configuration',
        displayName: 'Air To',
        checked: false,
        display: true,
        indeterminate: false,
        expand: false,
        field: '',
        children: [],
      },
      {
        name: 'Actuator Configuration',
        displayName: 'Actuator Size',
        checked: false,
        display: true,
        indeterminate: false,
        expand: false,
        field: 'actuator_size',
        children: [],
      },
      {
        name: 'Actuator Configuration',
        displayName: 'Spring Type',
        checked: false,
        display: true,
        indeterminate: false,
        expand: false,
        field: 'spring_type',
        children: [],
      },
      {
        name: 'Actuator Configuration',
        displayName: 'Bench Range Min',
        checked: false,
        display: true,
        indeterminate: false,
        expand: false,
        field: 'bench_range_min',
        children: [],
      },
      {
        name: 'Actuator Configuration',
        displayName: 'Bench Range Max',
        checked: false,
        display: true,
        indeterminate: false,
        expand: false,
        field: 'bench_range_max',
        children: [],
      },
    ],
  },
  {
    displayName: 'Repair Technician',
    name: 'General',
    expand: false,
    checked: false,
    indeterminate: false,
    display: true,
    field: '',
    children: [
      {
        display: true,
        indeterminate: false,
        expand: false,
        displayName: 'Name',
        name: 'Repair Technician',
        checked: false,
        field: 'name',
        children: [],
      },
      {
        name: 'Repair Technician',
        displayName: 'Phone',
        checked: false,
        display: true,
        indeterminate: false,
        expand: false,
        field: 'phone',
        children: [],
      },
      {
        name: 'Repair Technician',
        displayName: 'Email',
        checked: false,
        display: true,
        indeterminate: false,
        expand: false,
        field: 'email',
        children: [],
      },
    ],
  },
  {
    displayName: 'Scope of Work',
    name: 'General',
    expand: false,
    checked: false,
    indeterminate: false,
    display: true,
    field: '',
    children: [
      {
        display: true,
        indeterminate: false,
        expand: false,
        displayName: 'Event Type',
        name: 'Scope of Work',
        checked: false,
        field: 'event_type',
        children: [],
      },
    ],
  },
  {
    displayName: 'Final Test',
    name: 'CV',
    expand: false,
    checked: false,
    indeterminate: false,
    display: true,
    field: '',
    children: [
      {
        display: true,
        indeterminate: false,
        expand: false,
        displayName: 'Performed',
        name: 'Final Test',
        checked: false,
        field: 'final_test_performed',
        children: [],
      },
      {
        name: 'Final Test',
        displayName: 'Date',
        checked: false,
        display: true,
        indeterminate: false,
        expand: false,
        field: 'final_test_date',
        children: [],
      },
      {
        name: 'Final Test',
        displayName: 'Assembled By',
        checked: false,
        display: true,
        indeterminate: false,
        expand: false,
        field: 'final_test_assembled_by',
        children: [],
      },
      {
        name: 'Final Test',
        displayName: 'Tested By',
        checked: false,
        display: true,
        indeterminate: false,
        expand: false,
        field: 'final_test_tested_by',
        children: [],
      },
      {
        name: 'Final Test',
        displayName: 'Witnessed By',
        checked: false,
        display: true,
        indeterminate: false,
        expand: false,
        field: 'final_test_witnessed_by',
        children: [],
      },
      {
        name: 'Final Test',
        displayName: 'Gauge #',
        checked: false,
        display: true,
        indeterminate: false,
        expand: false,
        field: 'final_test_gauge',
        children: [],
      },
      {
        name: 'Final Test',
        displayName: 'Torque Wrench #',
        checked: false,
        display: true,
        indeterminate: false,
        expand: false,
        field: 'final_test_torque_wrench',
        children: [],
      },
      {
        name: 'Final Test',
        displayName: 'Comments',
        checked: false,
        display: true,
        indeterminate: false,
        expand: false,
        field: 'final_test_comments',
        children: [],
      },
    ],
  },
  {
    displayName: 'Final Test - Calibration/Functional Test',
    name: 'CV',
    expand: false,
    checked: false,
    indeterminate: false,
    display: true,
    field: '',
    children: [
      {
        display: true,
        indeterminate: false,
        expand: false,
        displayName: 'Performed',
        name: 'Final Test - Calibration/Functional Test',
        checked: false,
        field: 'calibration_test_performed',
        children: [],
      },
      {
        name: 'Final Test - Calibration/Functional Test',
        displayName: 'Comments',
        checked: false,
        display: true,
        indeterminate: false,
        expand: false,
        field: 'calibration_test_comments',
        children: [],
      },
    ],
  },
  {
    displayName: 'Final Inspection',
    name: 'CV',
    expand: false,
    checked: false,
    indeterminate: false,
    display: true,
    field: '',
    children: [
      {
        display: true,
        indeterminate: false,
        expand: false,
        displayName: 'Comments',
        name: 'Final Inspection',
        checked: false,
        field: 'final_inspection_comments',
        children: [],
      },
    ],
  },
];
